import { FilmList } from 'src/app/shared/classes/film-list';

const films: FilmList[] = [
  {
  id: 1,
  title: 'Cold War',
  year: '2018',
  released: '22 Mar 2019',
  runtime: '89 min',
  genre: 'Drama, History, Music, Romance',
  director: 'Pawel Pawlikowski',
  actors: 'Joanna Kulig, Tomasz Kot, Borys Szyc, Agata Kulesza',
  plot: 'In the 1950s, a music director falls in love with a singer and tries to persuade her to flee communist Poland for France.',
  language: 'Polish, French, German, Russian, Italian, Croatian',
  country: 'Poland, UK, France',
  awards: '1 nomination.',
  poster: 'https://m.media-amazon.com/images/M/MV5BNTJmNzExOGItZTQyMi00YzBlLTk0ZTQtNzAxYmUwZDQwZjU4XkEyXkFqcGdeQXVyODE1MjMyNzI@._V1_SX300.jpg',
  imdbRating: '7.6'
  },
  {
  id: 2,
  title: 'The Tree of Life',
  year: '2011',
  released: '17 May 2011',
  runtime: '139 min',
  genre: 'Drama, Fantasy',
  director: 'Terrence Malick',
  actors: 'Brad Pitt, Sean Penn, Jessica Chastain, Hunter McCracken',
  plot: 'The story of a family in Waco, Texas in 1956. The eldest son witnesses the loss of innocence and struggles with his parents\' conflicting teachings.',
  language: 'English',
  country: 'USA',
  awards: 'Nominated for 3 Oscars. Another 111 wins & 117 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BMTMwNjQ0NjMzN15BMl5BanBnXkFtZTcwNjMxMTkyNA@@._V1_SX300.jpg',
  imdbRating: '6.8'
  },
  {
  id: 3,
  title: 'In the Mood for Love',
  year: '2000',
  released: '09 Mar 2001',
  runtime: '98 min',
  genre: 'Drama, Romance',
  director: 'Kar-Wai Wong',
  actors: 'Maggie Cheung, Tony Chiu-Wai Leung, Ping Lam Siu, Tung Cho \'Joe\' Cheung',
  plot: 'Two neighbors, a woman and a man, form a strong bond after both suspect extramarital activities of their spouses. However, they agree to keep their bond platonic so as not to commit similar wrongs.',
  language: 'Cantonese, Shanghainese, French, Spanish',
  country: 'Hong Kong, China',
  awards: 'Nominated for 1 BAFTA Film Award. Another 44 wins & 47 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BYjZjODRlMjQtMjJlYy00ZDBjLTkyYTQtZGQxZTk5NzJhYmNmXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
  imdbRating: '8.1'
  },
  {
  id: 4,
  title: 'Happy Together',
  year: '1997',
  released: '30 May 1997',
  runtime: '96 min',
  genre: 'Drama, Romance',
  director: 'Kar-Wai Wong',
  actors: 'Leslie Cheung, Tony Chiu-Wai Leung, Chen Chang, Gregory Dayton',
  plot: 'A couple take a trip to Argentina but both men find their lives drifting apart in opposite directions.',
  language: 'Mandarin, Cantonese, Spanish',
  country: 'Hong Kong, Japan, South Korea',
  awards: '7 wins & 19 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BMTc4ODY4MjY2MF5BMl5BanBnXkFtZTcwNTE0MDMzNA@@._V1_SX300.jpg',
  imdbRating: '7.8'
  },
  {
  id: 5,
  title: 'Pulp Fiction',
  year: '1994',
  released: '14 Oct 1994',
  runtime: '154 min',
  genre: 'Crime, Drama',
  director: 'Quentin Tarantino',
  actors: 'Tim Roth, Amanda Plummer, Laura Lovelace, John Travolta',
  plot: 'The lives of two mob hitmen, a boxer, a gangster & his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
  language: 'English, Spanish, French',
  country: 'USA',
  awards: 'Won 1 Oscar. Another 62 wins & 69 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
  imdbRating: '8.9'
  },
  {
  id: 6,
  title: 'The Lives of Others',
  year: '2006',
  released: '30 Mar 2007',
  runtime: '137 min',
  genre: 'Drama, Thriller',
  director: 'Florian Henckel von Donnersmarck',
  actors: 'Martina Gedeck, Ulrich Mühe, Sebastian Koch, Ulrich Tukur',
  plot: 'In 1984 East Berlin, an agent of the secret police, conducting surveillance on a writer and his lover, finds himself becoming increasingly absorbed by their lives.',
  language: 'German',
  country: 'Germany',
  awards: 'Won 1 Oscar. Another 75 wins & 34 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BOThkM2EzYmMtNDE3NS00NjlhLTg4YzktYTdhNzgyOWY3ZDYzXkEyXkFqcGdeQXVyNzQzNzQxNzI@._V1_SX300.jpg',
  imdbRating: '8.4'
  },
  {
  id: 7,
  title: 'La Vendedora de Rosas',
  year: '1998',
  released: '17 September 1999',
  runtime: '116 min',
  genre: 'Drama',
  director: 'Víctor Gaviria',
  actors: 'Lady Tabares, Marta Correa, Monica Rodríguez, Mileider Gil',
  plot: 'Lady Tabares declares herself innocent before she enters the trial that will define her future. From the police car, she regards the street vendors through the window. One of them is a girl selling roses, just like she did ten years ago.',
  language: 'Spanish',
  country: 'Colombia',
  awards: 'N/A',
  poster: 'https://images-na.ssl-images-amazon.com/images/M/MV5BOWY4ZGIzMGQtODAyZC00NTYwLWE0ZWMtYWU4ZDM3M2Y1YThiXkEyXkFqcGdeQXVyNjc1NzA1MDA@._V1_SX300.jpg',
  imdbRating: '7.4'
  },
  {
  id: 8,
  title: 'In the Name of the Father',
  year: '1993',
  released: '25 Feb 1994',
  runtime: '133 min',
  genre: 'Biography, Drama',
  director: 'Jim Sheridan',
  actors: 'Alison Crosbie, Daniel Day-Lewis, Philip King, Emma Thompson',
  plot: 'A man\'s coerced confession to an IRA bombing he did not commit results in the imprisonment of his father as well. An English lawyer fights to free them.',
  language: 'English',
  country: 'Ireland, UK',
  awards: 'Nominated for 7 Oscars. Another 7 wins & 33 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BMmYyOTgwYWItYmU3Ny00M2E2LTk0NWMtMDVlNmQ0MWZiMTMxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
  imdbRating: '8.1'
  },
  {
  id: 9,
  title: 'The Magdalene Sisters',
  year: '2002',
  released: '29 Aug 2003',
  runtime: '114 min',
  genre: 'Drama',
  director: 'Peter Mullan',
  actors: 'Geraldine McEwan, Anne-Marie Duff, Nora-Jane Noone, Dorothy Duffy',
  plot: 'Three young Irish women struggle to maintain their spirits while they endure dehumanizing abuse as inmates of a Magdalene Sisters Asylum.',
  language: 'English, Latin',
  country: 'Ireland, UK',
  awards: 'Nominated for 1 BAFTA Film Award. Another 18 wins & 14 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BMTI2NzU1NTc1NF5BMl5BanBnXkFtZTcwOTQ1MjAwMQ@@._V1_SX300.jpg',
  imdbRating: '7.8'
  },
  {
  id: 10,
  title: 'The Full Monty',
  year: '1997',
  released: '19 Sep 1997',
  runtime: '91 min',
  genre: 'Comedy, Drama',
  director: 'Peter Cattaneo',
  actors: 'Robert Carlyle, Mark Addy, Wim Snape, Steve Huison',
  plot: 'Six unemployed steel workers form a male striptease act. The women cheer them on to go for "the full monty" - total nudity.',
  language: 'English',
  country: 'UK, USA',
  awards: 'Won 1 Oscar. Another 35 wins & 31 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BODg0NWFjMTAtNGZjMC00NmZlLThhZDYtM2MzNTU2NDZiZDVmXkEyXkFqcGdeQXVyMDUyOTUyNQ@@._V1_SX300.jpg',
  imdbRating: '7.2'
  },
  {
  id: 11,
  title: 'Amores Perros',
  year: '2000',
  released: '13 Apr 2001',
  runtime: '154 min',
  genre: 'Drama, Thriller',
  director: 'Alejandro G. Iñárritu',
  actors: 'Emilio Echevarría, Gael García Bernal, Goya Toledo, Álvaro Guerrero',
  plot: 'A horrific car accident connects three stories, each involving characters dealing with loss, regret, and life\'s harsh realities, all in the name of love.',
  language: 'Spanish',
  country: 'Mexico',
  awards: 'Nominated for 1 Oscar. Another 54 wins & 22 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BMWJhOTg5MWQtYTJjMi00YmFkLTg4ODgtYmU2YWVhODQ4ZDM3XkEyXkFqcGdeQXVyMTAwMzUyOTc@._V1_SX300.jpg',
  imdbRating: '8.1'
  },
  {
  id: 12,
  title: 'Reservoir Dogs',
  year: '1992',
  released: '02 Sep 1992',
  runtime: '99 min',
  genre: 'Crime, Drama, Thriller',
  director: 'Quentin Tarantino',
  actors: 'Harvey Keitel, Tim Roth, Michael Madsen, Chris Penn',
  plot: 'When a simple jewelry heist goes horribly wrong, the surviving criminals begin to suspect that one of them is a police informant.',
  language: 'English',
  country: 'USA',
  awards: '12 wins & 22 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BZmExNmEwYWItYmQzOS00YjA5LTk2MjktZjEyZDE1Y2QxNjA1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
  imdbRating: '8.3'
  },
  {
  id: 13,
  title: 'Manifesto',
  year: '2015',
  released: '23 Nov 2017',
  runtime: '95 min',
  genre: 'Drama',
  director: 'Julian Rosefeldt',
  actors: 'Cate Blanchett, Erika Bauer, Ruby Bustamante, Carl Dietrich',
  plot: 'Cate Blanchett performs manifestos as a series of striking monologues.',
  language: 'English',
  country: 'Germany',
  awards: '1 win & 2 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BNjU5MzA4YjMtOGQ4NS00MjAzLWEyOTUtMGQ0OTE5MjgxY2JmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
  imdbRating: '6.7'
  },
  {
  id: 14,
  title: 'The Matrix',
  year: '1999',
  released: '31 Mar 1999',
  runtime: '136 min',
  genre: 'Action, Sci-Fi',
  director: 'Lana Wachowski, Lilly Wachowski',
  actors: 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving',
  plot: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
  language: 'English',
  country: 'USA',
  awards: 'Won 4 Oscars. Another 34 wins & 48 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
  imdbRating: '8.7'
  },
  {
  id: 15,
  title: 'Mauvais Sang',
  year: '1986',
  released: '26 Nov 1986',
  runtime: '105 min',
  genre: 'Crime, Drama, Romance',
  director: 'Leos Carax',
  actors: 'Michel Piccoli, Juliette Binoche, Denis Lavant, Hans Meyer',
  plot: 'Marc (Michel Piccoli) recruits Alex (Denis Lavant), son of his former, now dead colleague. Alex is a card shark with a big dream to go out to the world and leave his own mark. His ...',
  language: 'French',
  country: 'France, Switzerland',
  awards: '3 wins & 5 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BMjIwODE4NzI2MF5BMl5BanBnXkFtZTgwMDE2NjQ3MDE@._V1_SX300.jpg',
  imdbRating: '7.3'
  },
  {
  id: 16,
  title: 'Taxi Driver',
  year: '1976',
  released: '08 Feb 1976',
  runtime: '114 min',
  genre: 'Crime, Drama',
  director: 'Martin Scorsese',
  actors: 'Diahnne Abbott, Frank Adu, Victor Argo, Gino Ardito',
  plot: 'A mentally unstable veteran works as a nighttime taxi driver in New York City, where the perceived decadence and sleaze fuels his urge for violent action by attempting to liberate a presidential campaign worker and an underage prostitute.',
  language: 'English, Spanish',
  country: 'USA',
  awards: 'Nominated for 4 Oscars. Another 21 wins & 15 nominations.',
  poster: 'https://www.joblo.com/assets/images/oldsite/posters/images/full/taxi-driver-poster2.jpg',
  imdbRating: '8.3'
   },
   {
  id: 17,
  title: 'Fargo',
  year: '1996',
  released: '05 Apr 1996',
  runtime: '98 min',
  genre: 'Crime, Drama, Thriller',
  director: 'Joel Coen, Ethan Coen',
  actors: 'William H. Macy, Steve Buscemi, Peter Stormare, Kristin Rudrüd',
  plot: 'Jerry Lundegaard\'s inept crime falls apart due to his and his henchmen\'s bungling and the persistent police work of the quite pregnant Marge Gunderson.',
  language: 'English',
  country: 'USA, UK',
  awards: 'Won 2 Oscars. Another 79 wins & 59 nominations.',
  poster: 'https://www.joblo.com/assets/images/oldsite/posters/images/full/1996-fargo-poster2.jpg',
  imdbRating: '8.1'
  },
  {
  id: 18,
  title: 'Do the Right Thing',
  year: '1989',
  released: '21 Jul 1989',
  runtime: '120 min',
  genre: 'Comedy, Drama',
  director: 'Spike Lee',
  actors: 'Danny Aiello, Ossie Davis, Ruby Dee, Richard Edson',
  plot: 'On the hottest day of t year on a street in the Bedford-Stuyvesant section of Brooklyn, everyone\'s hate and bigotry smolders and builds until it explodes into violence.',
  language: 'English, Italian, Spanish, Korean',
  country: 'USA',
  awards: 'Nominated for 2 Oscars. Another 18 wins & 14 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BODA2MjU1NTI1MV5BMl5BanBnXkFtZTgwOTU4ODIwMjE@._V1_SX300.jpg',
  imdbRating: '7.9'
  },
  {
  id: 19,
  title: 'Raging Bull',
  year: '1980',
  released: '19 Dec 1980',
  runtime: '129 min',
  genre: 'Biography, Drama, Sport',
  director: 'Martin Scorsese',
  actors: 'Robert De Niro, Cathy Moriarty, Joe Pesci, Frank Vincent',
  plot: 'The life of boxer Jake LaMotta, who\'s violence and temper that lead him to the top in the ring destroyed his life outside of it.',
  language: 'English',
  country: 'USA',
  awards: 'Won 2 Oscars. Another 22 wins & 26 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BYjRmODkzNDItMTNhNi00YjJlLTg0ZjAtODlhZTM0YzgzYThlXkEyXkFqcGdeQXVyNzQ1ODk3MTQ@._V1_SX300.jpg',
  imdbRating: '8.2'
  },
  {
  id: 20,
  title: 'Manhattan',
  year: '1979',
  released: '25 Apr 1979',
  runtime: '96 min',
  genre: 'Comedy, Drama, Romance',
  director: 'Woody Allen',
  actors: 'Woody Allen, Diane Keaton, Michael Murphy, Mariel Hemingway',
  plot: 'The life of a divorced television writer dating a teenage girl is further complicated when he falls in love with his best friend\'s mistress.',
  language: 'English',
  country: 'USA',
  awards: 'Nominated for 2 Oscars. Another 15 wins & 21 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BMzdmY2I3MmEtOGFiZi00MTg1LWIxY2QtNWUwM2NmNWNlY2U5XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg',
  imdbRating: '8.0'
  },
  {
  id: 21,
  title: 'Deconstructing Harry',
  year: '1997',
  released: '02 Jan 1998',
  runtime: '96 min', genre: 'Comedy',
  director: 'Woody Allen',
  actors: 'Judy Davis, Julia Louis-Dreyfus, Stephanie Roth Haberle, Dan Frazer',
  plot: 'Suffering from writer\'s block and eagerly awaiting his writing award, Harry Block remembers events from his past and scenes from his best-selling books as characters, real and fictional, come back to haunt him.',
  language: 'English, Hebrew',
  country: 'USA',
  awards: 'Nominated for 1 Oscar. Another 2 wins & 4 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BMDVjZWJiYzAtMWJkOS00ZDQzLTlkYTItYmMwMGE3YmY1MjQ3XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
  imdbRating: '7.4'
  },
  {
  id: 22,
  title: 'The Godfather',
  year: '1972',
  released: '24 Mar 1972',
  runtime: '175 min',
  genre: 'Crime, Drama',
  director: 'Francis Ford Coppola',
  actors: 'Marlon Brando, Al Pacino, James Caan, Richard S. Castellano',
  plot: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
  language: 'English, Italian, Latin',
  country: 'USA',
  awards: 'Won 3 Oscars. Another 24 wins & 28 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
  imdbRating: '9.2'
  },
  {
  id: 23,
  title: 'The Godfather: Part II',
  year: '1974',
  released: '20 Dec 1974',
  runtime: '202 min',
  genre: 'Crime, Drama',
  director: 'Francis Ford Coppola',
  actors: 'Al Pacino, Robert Duvall, Diane Keaton, Robert De Niro',
  plot: 'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.',
  language: 'English, Italian, Spanish, Latin, Sicilian',
  country: 'USA',
  awards: 'Won 6 Oscars. Another 11 wins & 20 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
  imdbRating: '9.0'
  },
  {
  id: 24,
  title: '8 Women',
  year: '2002',
  released: '04 Oct 2002',
  runtime: '111 min',
  genre: 'Comedy, Crime, Musical, Romance',
  director: 'François Ozon',
  actors: 'Virginie Ledoyen, Danielle Darrieux, Firmine Richard, Catherine Deneuve',
  plot: 'One murdered man, eight women, each seeming to be eager than the others to know the truth. Gimme, gimme, gimme some clues to make up my mind. And eventually enter the truth. Oh, thou cruel woman!',
  language: 'French, English',
  country: 'France, Italy',
  awards: '11 wins & 30 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BMTJkYTg4N2MtMzcwMy00ZjFiLWFlNzItMmJhMTllZjI2YjRlXkEyXkFqcGdeQXVyNzA5NjUyNjM@._V1_SX300.jpg',
  imdbRating: '7.1'
  },
  {
  id: 25,
  title: 'The Hours',
  year: '2002',
  released: '14 Feb 2003',
  runtime: '110 min',
  genre: 'Drama, Romance',
  director: 'Stephen Daldry',
  actors: 'Nicole Kidman, Julianne Moore, Meryl Streep, Stephen Dillane',
  plot: 'The story of how the novel "Mrs. Dalloway" affects three generations of women, all of whom, in one way or another, have had to deal with suicide in their lives.',
  language: 'English',
  country: 'USA, UK',
  awards: 'Won 1 Oscar. Another 41 wins & 125 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BMTY4MDQyNjM2OF5BMl5BanBnXkFtZTcwMjQxOTAzMw@@._V1_SX300.jpg',
  imdbRating: '7.6'
  },
  {
  id: 26,
  title: 'Donnie Darko',
  year: '2001',
  released: '26 Oct 2001',
  runtime: '113 min',
  genre: 'Drama, Sci-Fi, Thriller',
  director: 'Richard Kelly',
  actors: 'Jake Gyllenhaal, Holmes Osborne, Maggie Gyllenhaal, Daveigh Chase',
  plot: 'A troubled teenager is plagued by visions of a man in a large rabbit suit who manipulates him to commit a series of crimes, after he narrowly escapes a bizarre accident.',
  language: 'English',
  country: 'USA',
  awards: '11 wins & 15 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BZjZlZDlkYTktMmU1My00ZDBiLWFlNjEtYTBhNjVhOTM4ZjJjXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
  imdbRating: '8.1'
  },
  {
  id: 27,
  title: 'Babel', year: '2006',
  released: '10 Nov 2006',
  runtime: '143 min',
  genre: 'Drama',
  director: 'Alejandro G. Iñárritu',
  actors: 'Brad Pitt, Cate Blanchett, Mohamed Akhzam, Peter Wight',
  plot: 'Tragedy strikes a married couple on vacation in the Moroccan desert, touching off an interlocking story involving four different families.',
  language: 'English, Arabic, Spanish, Japanese, Berber languages, French, Russian, Japanese Sign language',
  country: 'France, USA, Mexico',
  awards: 'Won 1 Oscar. Another 41 wins & 134 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BYTJkZDljNGYtNjRiNC00ZmY2LTg1NmItYTI1MTllNDQzMWVmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
  imdbRating: '7.5'
  },
  {
  id: 28,
  title: '21 Grams',
  year: '2003',
  released: '16 Jan 2004',
  runtime: '124 min',
  genre: 'Crime, Drama, Thriller',
  director: 'Alejandro G. Iñárritu',
  actors: 'Sean Penn, Naomi Watts, Danny Huston, Carly Nahon',
  plot: 'A freak accident brings together a critically ill mathematician, a grieving mother, and a born-again ex-con.',
  language: 'English',
  country: 'USA',
  awards: 'Nominated for 2 Oscars. Another 30 wins & 76 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BMjA4MjI2OTM5N15BMl5BanBnXkFtZTcwNDA1NjUzMw@@._V1_SX300.jpg',
  imdbRating: '7.7'
},
  {
  id: 29,
  title: 'Roma',
  year: '2018',
  released: '21 Nov 2018',
  runtime: '135 min',
  genre: 'Drama',
  director: 'Alfonso Cuarón',
  actors: 'Yalitza Aparicio, Marina de Tavira, Diego Cortina Autrey, Carlos Peralta',
  plot: 'A year in the life of a middle-class family\'s maid in Mexico City in the early 1970s.',
  language: 'Spanish, Mixtec, English, Japanese, German, French, Norwegian',
  country: 'Mexico, USA',
  awards: 'N/A',
  poster: 'https://m.media-amazon.com/images/M/MV5BMTU0OTc3ODk4Ml5BMl5BanBnXkFtZTgwMzM4NzI5NjM@._V1_SX300.jpg',
  imdbRating: '7.8'
  },
  {
  id: 30,
  title: 'Scarface',
  year: '1983',
  released: '09 Dec 1983',
  runtime: '170 min',
  genre: 'Crime, Drama',
  director: 'Brian De Palma',
  actors: 'Al Pacino, Steven Bauer, Michelle Pfeiffer, Mary Elizabeth Mastrantonio',
  plot: 'In Miami in 1980, a determined Cuban immigrant takes over a drug cartel and succumbs to greed.',
  language: 'English, Spanish',
  country: 'USA',
  awards: 'Nominated for 3 Golden Globes. Another 4 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BNjdjNGQ4NDEtNTEwYS00MTgxLTliYzQtYzE2ZDRiZjFhZmNlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
  imdbRating: '8.3'
  },
  {
  id: 31,
  title: 'Marie Antoinette',
  year: '2006',
  released: '20 Oct 2006',
  runtime: '123 min',
  genre: 'Biography, Drama, History, Romance',
  director: 'Sofia Coppola',
  actors: 'Kirsten Dunst, Jason Schwartzman, Judy Davis, Rip Torn',
  plot: 'The retelling of France\'s iconic but ill-fated queen, Marie Antoinette. From her betrothal and marriage to Louis XVI at 15 to her reign as queen at 19 and to the end of her reign as queen, and ultimately the fall of Versailles.',
  language: 'English, Latin, French',
  country: 'USA, France, Japan',
  awards: 'Won 1 Oscar. Another 18 wins & 23 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BMTA5MzFhMjAtMDJhMC00YzVhLTlkMzAtMDEyOGE0NjIzZTU2XkEyXkFqcGdeQXVyMjA5MTIzMjQ@._V1_SX300.jpg',
  imdbRating: '6.4'
  },
  {
  id: 32,
  title: 'Eternal Sunshine of the Spotless Mind',
  year: '2004',
  released: '19 Mar 2004',
  runtime: '108 min',
  genre: 'Drama, Romance, Sci-Fi',
  director: 'Michel Gondry',
  actors: 'Jim Carrey, Kate Winslet, Gerry Robert Byrne, Elijah Wood',
  plot: 'When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories.',
  language: 'English',
  country: 'USA',
  awards: 'Won 1 Oscar. Another 71 wins & 109 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BMTY4NzcwODg3Nl5BMl5BanBnXkFtZTcwNTEwOTMyMw@@._V1_SX300.jpg',
  imdbRating: '8.3'
  },
  {
  id: 33,
  title: 'Y Tu Mamá También',
  year: '2001',
  released: '26 Apr 2002',
  runtime: '106 min',
  genre: 'Adventure, Comedy, Drama',
  director: 'Alfonso Cuarón',
  actors: 'Daniel Giménez Cacho, Ana López Mercado, Diego Luna, Gael García Bernal',
  plot: 'In Mexico, two teenage boys and an attractive older woman embark on a road trip and learn a thing or two about life, friendship, sex, and each other.',
  language: 'Spanish',
  country: 'Mexico',
  awards: 'Nominated for 1 Oscar. Another 37 wins & 45 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BNDhjMzc3ZTgtY2Y4MC00Y2U3LWFiMDctZGM3MmM4N2YzNDQ5XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
  imdbRating: '7.7'
  },
  {
  id: 34,
  title: 'Inside Out', year: '2015',
  released: '19 Jun 2015',
  runtime: '95 min',
  genre: 'Animation, Adventure, Comedy, Drama, Family, Fantasy',
  director: 'Pete Docter, Ronnie Del Carmen(co-director)',
  actors: 'Amy Poehler, Phyllis Smith, Richard Kind, Bill Hader',
  plot: 'After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions - Joy, Fear, Anger, Disgust and Sadness - conflict on how best to navigate a new city, house, and school.',
  language: 'English',
  country: 'USA',
  awards: 'Won 1 Oscar. Another 93 wins & 112 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BOTgxMDQwMDk0OF5BMl5BanBnXkFtZTgwNjU5OTg2NDE@._V1_SX300.jpg',
  imdbRating: '8.2'
  },
  {
  id: 35,
  title: 'Belle de Jour', year: '1967',
  released: '10 Apr 1968',
  runtime: '100 min',
  genre: 'Drama',
  director: 'Luis Buñuel',
  actors: 'Catherine Deneuve, Jean Sorel, Michel Piccoli, Geneviève Page',
  plot: 'A frigid young housewife decides to spend her midweek afternoons as a prostitute.',
  language: 'French, Spanish, Mongolian',
  country: 'France, Italy',
  awards: 'Nominated for 1 BAFTA Film Award. Another 5 wins & 2 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BZjNkNGJjYWEtM2IyNi00ZjM5LWFlYjYtYjQ4NTU5MGFlMTI2XkEyXkFqcGdeQXVyMTMxMTY0OTQ@._V1_SX300.jpg',
  imdbRating: '7.8'
  },
  {
  id: 36,
  title: 'Jurassic Park',
  year: '1993',
  released: '11 Jun 1993',
  runtime: '127 min',
  genre: 'Adventure, Sci-Fi, Thriller',
  director: 'Steven Spielberg',
  actors: 'Sam Neill, Laura Dern, Jeff Goldblum, Richard Attenborough',
  plot: 'During a preview tour, a theme park suffers a major power breakdown that allows its cloned dinosaur exhibits to run amok.',
  language: 'English, Spanish',
  country: 'USA',
  awards: 'Won 3 Oscars. Another 32 wins & 25 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_SX300.jpg',
  imdbRating: '8.1'
  },
  {
  id: 37,
  title: 'No country for Old Men',
  year: '2007',
  released: '21 Nov 2007',
  runtime: '122 min',
  genre: 'Crime, Drama, Thriller',
  director: 'Ethan Coen, Joel Coen',
  actors: 'Tommy Lee Jones, Javier Bardem, Josh Brolin, Woody Harrelson',
  plot: 'Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande.',
  language: 'English, Spanish',
  country: 'USA',
  awards: 'Won 4 Oscars. Another 157 wins & 132 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BMjA5Njk3MjM4OV5BMl5BanBnXkFtZTcwMTc5MTE1MQ@@._V1_SX300.jpg',
  imdbRating: '8.1'
  },
  {
  id: 38,
  title: 'Inglourious Basterds',
  year: '2009',
  released: '21 Aug 2009',
  runtime: '153 min',
  genre: 'Adventure, Drama, War',
  director: 'Quentin Tarantino',
  actors: 'Brad Pitt, Mélanie Laurent, Christoph Waltz, Eli Roth',
  plot: 'In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner\'s vengeful plans for the same.',
  language: 'English, German, French, Italian',
  country: 'Germany, USA',
  awards: 'Won 1 Oscar. Another 129 wins & 165 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BOTJiNDEzOWYtMTVjOC00ZjlmLWE0NGMtZmE1OWVmZDQ2OWJhXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg',
  imdbRating: '8.3'
  },
  {
  id: 39,
  title: 'Funny Games',
  year: '1997',
  released: '11 Mar 1998',
  runtime: '108 min',
  genre: 'Crime, Drama, Horror, Thriller',
  director: 'Michael Haneke',
  actors: 'Susanne Lothar, Ulrich Mühe, Arno Frisch, Frank Giering',
  plot: 'Two violent young men take a mother, father, and son hostage in their vacation cabin and force them to play sadistic "games" with one another for their own amusement.',
  language: 'German, French, Italian',
  country: 'Austria',
  awards: '4 wins & 6 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BM2ZhZDlmZDMtMDk5OC00YjhiLTgxOTAtYWEwMzhiMjJhMmEwL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
  imdbRating: '7.6'
  },
  {
  id: 40,
  title: 'The Piano Teacher',
  year: '2001',
  released: '05 Sep 2001',
  runtime: '131 min',
  genre: 'Drama, Music',
  director: 'Michael Haneke',
  actors: 'Isabelle Huppert, Annie Girardot, Benoît Magimel, Susanne Lothar',
  plot: 'A young man romantically pursues his masochistic piano teacher.',
  language: 'French, German',
  country: 'Austria, France, Germany',
  awards: 'Nominated for 1 BAFTA Film Award. Another 17 wins & 21 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BZDBkYjYxYjUtMTdmMS00MDJhLWEyNzktYzg2OWY5NWY0Y2QyL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNDkzNTM2ODg@._V1_SX300.jpg',
  imdbRating: '7.5'
  },
  {
  id: 41,
  title: 'Antichrist',
  year: '2009',
  released: '20 May 2009',
  runtime: '108 min',
  genre: 'Drama, Horror',
  director: 'Lars von Trier',
  actors: 'Willem Dafoe, Charlotte Gainsbourg, Storm Acheche Sahlstrøm',
  plot: 'A grieving couple retreat to their cabin in the woods, hoping to repair their broken hearts and troubled marriage, but nature takes its course and things go from bad to worse.',
  language: 'English',
  country: 'Denmark, Germany, France, Sweden, Italy, Poland',
  awards: '21 wins & 30 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BMjE3MjQ2ODc1N15BMl5BanBnXkFtZTcwNjYyMzI5Mg@@._V1_SX300.jpg',
  imdbRating: '6.6'
  },
  {
  id: 42,
  title: 'Melancholia',
  year: '2011',
  released: '26 May 2011',
  runtime: '135 min',
  genre: 'Drama, Sci-Fi',
  director: 'Lars von Trier',
  actors: 'Kirsten Dunst, Charlotte Gainsbourg, Alexander Skarsgård, Brady Corbet',
  plot: 'Two sisters find their already strained relationship challenged as a mysterious new planet threatens to collide with Earth.',
  language: 'English',
  country: 'Denmark, Sweden, France, Germany',
  awards: '34 wins & 89 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BMTk4NjM0MjI3MV5BMl5BanBnXkFtZTcwNjcxMDYzNg@@._V1_SX300.jpg',
  imdbRating: '7.2'
  },
  {
  id: 43,
  title: 'Interstellar',
  year: '2014',
  released: '07 Nov 2014',
  runtime: '169 min',
  genre: 'Adventure, Drama, Sci-Fi',
  director: 'Christopher Nolan',
  actors: 'Ellen Burstyn, Matthew McConaughey, Mackenzie Foy, John Lithgow',
  plot: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
  language: 'English',
  country: 'USA, UK, Canada',
  awards: 'Won 1 Oscar. Another 43 wins & 143 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
  imdbRating: '8.6'
  },
  {
  id: 44,
  title: 'A Clockwork Orange',
  year: '1971',
  released: '02 Feb 1972',
  runtime: '136 min',
  genre: 'Crime, Drama, Sci-Fi',
  director: 'Stanley Kubrick',
  actors: 'Malcolm McDowell, Patrick Magee, Michael Bates, Warren Clarke',
  plot: 'In the future, a sadistic gang leader is imprisoned and volunteers for a conduct-aversion experiment, but it doesn\'t go as planned.',
  language: 'English',
  country: 'UK, USA',
  awards: 'Nominated for 4 Oscars. Another 9 wins & 19 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BMTY3MjM1Mzc4N15BMl5BanBnXkFtZTgwODM0NzAxMDE@._V1_SX300.jpg',
  imdbRating: '8.3'
  },
  {
  id: 45,
  title: 'Full Metal Jacket',
  year: '1987',
  released: '10 Jul 1987',
  runtime: '116 min',
  genre: 'Drama, War',
  director: 'Stanley Kubrick',
  actors: 'Matthew Modine, Adam Baldwin, Vincent D\'Onofrio, R. Lee Ermey',
  plot: 'A pragmatic U.S. Marine observes the dehumanizing effects the Vietnam War has on his fellow recruits from their brutal boot camp training to the bloody street fighting in Hue.',
  language: 'English, Vietnamese',
  country: 'UK, USA',
  awards: 'Nominated for 1 Oscar. Another 7 wins & 11 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BNzkxODk0NjEtYjc4Mi00ZDI0LTgyYjEtYzc1NDkxY2YzYTgyXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
  imdbRating: '8.3'
  },
  {
  id: 46,
  title: 'Dunkirk',
  year: '2017',
  released: '21 Jul 2017',
  runtime: '106 min',
  genre: 'Action, Drama, History, Thriller, War',
  director: 'Christopher Nolan',
  actors: 'Fionn Whitehead, Damien Bonnard, Aneurin Barnard, Lee Armstrong',
  plot: 'Allied soldiers from Belgium, the British Empire, and France are surrounded by the German Army, and evacuated during a fierce battle in World War II.',
  language: 'English, French, German',
  country: 'UK, Netherlands, France, USA',
  awards: 'Won 3 Oscars. Another 51 wins & 197 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BN2YyZjQ0NTEtNzU5MS00NGZkLTg0MTEtYzJmMWY3MWRhZjM2XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_SX300.jpg',
  imdbRating: '7.9'
  },
  {
  id: 47,
  title: 'The Florida Project',
  year: '2017',
  released: '10 Nov 2017',
  runtime: '111 min',
  genre: 'Drama',
  director: 'Sean Baker',
  actors: 'Brooklynn Prince, Christopher Rivera, Aiden Malik, Josie Olivo',
  plot: 'Set over one summer, the film follows precocious s-year-old Moonee as she courts mischief and adventure with her ragtag playmates and bonds with her rebellious but caring mother, all while living in the shadows of Walt Disney World.',
  language: 'English, Spanish, Portuguese',
  country: 'USA',
  awards: 'Nominated for 1 Oscar. Another 58 wins & 106 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BMjg4ZmY1MmItMjFjOS00ZTg2LWJjNDYtNDM2YmM2NzhiNmZhXkEyXkFqcGdeQXVyNTAzMTY4MDA@._V1_SX300.jpg',
  imdbRating: '7.6'
  },
  {
  id: 48,
  title: 'Moonlight',
  year: '2016',
  released: '18 Nov 2016',
  runtime: '111 min',
  genre: 'Drama',
  director: 'Barry Jenkins',
  actors: 'Mahershala Ali, Shariff Earp, Duan Sanderson, Alex R. Hibbert',
  plot: 'A chronicle of the childhood, adolescence and burgeoning adulthood of a young, African-American, gay man growing up in a rough neighborhood of Miami.',
  language: 'English',
  country: 'USA',
  awards: 'Won 3 Oscars. Another 220 wins & 270 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BNzQxNTIyODAxMV5BMl5BanBnXkFtZTgwNzQyMDA3OTE@._V1_SX300.jpg',
  imdbRating: '7.4'
  },
  {
  id: 49,
  title: 'Water Drops on Burning Rocks',
  year: '2000',
  released: '15 Mar 2000',
  runtime: '82 min',
  genre: 'Comedy, Drama, Romance',
  director: 'François Ozon',
  actors: 'Bernard Giraudeau, Malik Zidi, Ludivine Sagnier, Anna Levine',
  plot: 'In 1970s Germany, a -year-old businessman falls in love with a -year-old man.',
  language: 'French, German',
  country: 'France',
  awards: '2 wins & 2 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BMjE4MTk1NTAyOV5BMl5BanBnXkFtZTcwOTk3MTQyMQ@@._V1_SX300.jpg',
  imdbRating: '6.9'
  },
  {
  id: 50,
  title: 'Monsters, Inc.',
  year: '2001',
  released: '02 Nov 2001',
  runtime: '92 min',
  genre: 'Animation, Adventure, Comedy, Family, Fantasy',
  director: 'Pete Docter, David Silverman(co-director), Lee Unkrich(co-director)',
  actors: 'John Goodman, Billy Crystal, Mary Gibbs, Steve Buscemi',
  plot: 'In order to power the city, monsters have to scare children so that they scream. However, the children are toxic to the monsters, and after a child gets through, 2 monsters realize things may not be what they think.',
  language: 'English',
  country: 'USA',
  awards: 'Won 1 Oscar. Another 13 wins & 38 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BMTY1NTI0ODUyOF5BMl5BanBnXkFtZTgwNTEyNjQ0MDE@._V1_SX300.jpg',
  imdbRating: '8.1'
  },
  {
  id: 51,
  title: 'Coco',
  year: '2017',
  released: '22 Nov 2017',
  runtime: '105 min',
  genre: 'Animation, Adventure, Comedy, Family, Fantasy, Music, Mystery',
  director: 'Lee Unkrich, Adrian Molina(co-director)',
  actors: 'Anthony Gonzalez, Gael García Bernal, Benjamin Bratt, Alanna Ubach',
  plot: 'Aspiring musician Miguel, confronted with his family\'s ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.',
  language: 'English, Spanish',
  country: 'USA',
  awards: 'Won 2 Oscars. Another 86 wins & 28 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BYjQ5NjM0Y2YtNjZkNC00ZDhkLWJjMWItN2QyNzFkMDE3ZjAxXkEyXkFqcGdeQXVyODIxMzk5NjA@._V1_SX300.jpg',
  imdbRating: '8.4'
  },
  {
  id: 52,
  title: 'Dogville',
  year: '2003',
  released: '23 Apr 2004',
  runtime: '178 min',
  genre: 'Crime, Drama',
  director: 'Lars von Trier',
  actors: 'Nicole Kidman, Harriet Andersson, Lauren Bacall, Jean-Marc Barr',
  plot: 'A woman on the run from the mob is reluctantly accepted in a small Colorado town. In exchange, she agrees to work for them. As a search visits the town, she finds out that their support has a price. Yet her dangerous secret is never far away.',
  language: 'English',
  country: 'Denmark, Netherlands, Sweden, Germany, UK, France, Finland, Norway, Italy',
  awards: '20 wins & 31 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BMTkwNTg2MTI1NF5BMl5BanBnXkFtZTcwMDM1MzUyMQ@@._V1_SX300.jpg',
  imdbRating: '8.0'
  },
  {
  id: 53,
  title: 'Call Me by Your Name',
  year: '2017',
  released: '19 Jan 2018',
  runtime: '132 min',
  genre: 'Drama, Romance',
  director: 'Luca Guadagnino',
  actors: 'Armie Hammer, Timothée Chalamet, Michael Stuhlbarg, Amira Casar',
  plot: 'In 1980s Italy, a romance blossoms between a sevente-year-old student and the older man hired as his father\'s research assistant.',
  language: 'English, Italian, French, German, Hebrew',
  country: 'Italy, France',
  awards: 'Won 1 Oscar. Another 82 wins & 196 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BNDk3NTEwNjc0MV5BMl5BanBnXkFtZTgwNzYxNTMwMzI@._V1_SX300.jpg',
  imdbRating: '7.9'
  },
  {
  id: 54,
  title: 'Isle of Dogs',
  year: '2018',
  released: '13 Apr 2018',
  runtime: '101 min',
  genre: 'Animation, Adventure, Comedy, Drama, Fantasy, Sci-Fi',
  director: 'Wes Anderson',
  actors: 'Bryan Cranston, Koyu Rankin, Edward Norton, Bob Balaban',
  plot: 'Set in Japan, Isle of Dogs follows a boy\'s odyssey in search of his lost dog.',
  language: 'English, Japanese',
  country: 'Germany, USA',
  awards: '2 wins.',
  poster: 'https://m.media-amazon.com/images/M/MV5BMTYyOTUwNjAxM15BMl5BanBnXkFtZTgwODcyMzE0NDM@._V1_SX300.jpg',
  imdbRating: '7.9'
  },
  {
  id: 55,
  title: 'Head-On',
  year: '2004',
  released: '11 Mar 2004',
  runtime: '121 min',
  genre: 'Drama, Romance',
  director: 'Fatih Akin',
  actors: 'Birol Ünel, Güven Kiraç, Zarah Jane McKenzie, Stefan Gebelhoff',
  plot: 'With the intention to break free from the strict familial restrictions, a suicidal young woman sets up a marriage of convenience with a for-year-old addict, an act that will lead to an outburst of envious love.',
  language: 'German, Turkish, English',
  country: 'Germany, Turkey',
  awards: '25 wins & 13 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BODBiNzYxNzYtMjkyMi00MjUyLWJkM2YtZjNkMDhhYmEwMTRiL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg',
  imdbRating: '7.9'
  },
  {
  id: 56,
  title: 'A Prophet',
  year: '2009',
  released: '26 Mar 2010',
  runtime: '155 min',
  genre: 'Crime, Drama',
  director: 'Jacques Audiard',
  actors: 'Tahar Rahim, Niels Arestrup, Adel Bencherif, Reda Kateb',
  plot: 'A young Arab man is sent to a French prison.',
  language: 'French, Arabic, Corsican',
  country: 'France, Italy',
  awards: 'Nominated for 1 Oscar. Another 48 wins & 49 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BMTUyMjQ1MTY5OV5BMl5BanBnXkFtZTcwNzY5NjExMw@@._V1_SX300.jpg',
  imdbRating: '7.9'
  },
  {
  id: 57,
  title: 'Women on the Verge of a Nervous Breakdown',
  year: '1988',
  released: '11 Nov 1988',
  runtime: '88 min',
  genre: 'Comedy, Drama',
  director: 'Pedro Almodóvar',
  actors: 'Carmen Maura, Antonio Banderas, Julieta Serrano, María Barranco',
  plot: 'A television actress encounters a variety of eccentric characters after embarking on a journey to discover why her lover abruptly left her.',
  language: 'Spanish',
  country: 'Spain',
  awards: 'Nominated for 1 Oscar. Another 21 wins & 22 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BYWM1NWFjMDItODg5OS00MWUwLWFjNWUtOGZkZWM3NmRiMWNjXkEyXkFqcGdeQXVyMTA0MjU0Ng@@._V1_SX300.jpg',
  imdbRating: '7.6'
  },
  {
  id: 58,
  title: 'Volver',
  year: '2006',
  released: '26 Jan 2007',
  runtime: '121 min',
  genre: 'Comedy, Drama',
  director: 'Pedro Almodóvar',
  actors: 'Penélope Cruz, Carmen Maura, Lola Dueñas, Blanca Portillo',
  plot: 'After her death, a mother returns to her home town in order to fix the situations she couldn\'t resolve during her life.',
  language: 'Spanish',
  country: 'Spain',
  awards: 'Nominated for 1 Oscar. Another 60 wins & 90 nominations.',
  poster: 'https://m.media-amazon.com/images/M/MV5BMjA0NTUxMjY1OV5BMl5BanBnXkFtZTcwNjI2OTMzMQ@@._V1_SX300.jpg',
  imdbRating: '7.6'
  },
  { id: 59,
    title: 'All About My Mother',
    year: '1999',
    released: '31 Mar 2000',
    runtime: '101 min',
    genre: 'Drama',
    director: 'Pedro Almodóvar',
    actors: 'Cecilia Roth, Marisa Paredes, Candela Peña, Antonia San Juan',
    plot: 'Young Esteban wants to become a writer and also to discover the identity of his second mother, a trans woman, carefully concealed by his mother Manuela.',
    language: 'Spanish, Catalan',
    country: 'Spain, France',
    awards: 'Won 1 Oscar. Another 56 wins & 38 nominations.',
    poster: 'https://m.media-amazon.com/images/M/MV5BZTk2ZTMzMmUtZjUyNi00YzMyLWE3NTAtNDNjNzU3MGQ1YTFjXkEyXkFqcGdeQXVyMTA0MjU0Ng@@._V1_SX300.jpg',
    imdbRating: '7.9'
  }
];


export {films};
